# users dockercompose

services:
  users_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: adamwentworth/users_service:latest
    container_name: users_service
    env_file:
      - .env
    ports:
      - "127.0.0.1:3005:3005"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3005/readyz"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - kafka_default
    volumes:
      - ./app.log:/app/app.log  # Optional: persist logs

networks:
  kafka_default:
    external: true
