# events docker compose

services:
  events_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: adamwentworth/events_service:latest
    container_name: events_service
    env_file:
      - .env
    ports:
      - "127.0.0.1:3008:3008"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3008/readyz"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - kafka_default  # same external network used by MySQL and Kafka

networks:
  kafka_default:
    external: true
