version: 1
formatters:
  simple:
    format: '%(asctime)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  detailed:
    format: '%(asctime)s - %(levelname)s - trace_id: %(trace_id)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

filters:
  add_trace_id:
    (): storage.logging_filters.AddTraceIDFilter
  exclude_sql:
    (): storage.logging_filters.SQLFilter

handlers:
  console:
    class: logging.StreamHandler
    level: INFO  # Show only INFO level logs and higher
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: INFO  # Write only INFO level logs and higher
    formatter: detailed
    filters: [add_trace_id, exclude_sql]
    filename: 'storage/app.log'

loggers:
  basicLogger:
    level: DEBUG
    handlers: [console]
    propagate: no
  fileLogger:
    level: DEBUG
    handlers: [file]
    propagate: no
  backupLogger:
    level: DEBUG
    handlers: [console, file]
    propagate: no
  apscheduler:
    level: WARNING
    handlers: [console, file]
    propagate: no
  django.db.backends:  # New logger for Django database backend
    level: INFO  # Change to INFO to exclude SQL DEBUG queries
    handlers: [console, file]
    propagate: no

root:
  level: DEBUG
  handlers: [console, file]