global:
  smtp_smarthost: "smtp.gmail.com:587"
  smtp_from: "${ALERT_EMAIL_FROM}"
  smtp_auth_username: "${ALERT_EMAIL_USER}"
  smtp_auth_password: "${ALERT_EMAIL_PASS}"
  smtp_require_tls: true

route:
  group_by: ["alertname", "service"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: "noop"
  routes:
    - matchers:
        - severity="critical"
      receiver: "severe-email"

receivers:
  - name: "noop"

  - name: "severe-email"
    email_configs:
      - to: "adamjohnwentworth@gmail.com"
        send_resolved: true
