global:
  scrape_interval: 15s

rule_files:
  - alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "auth_service"
    metrics_path: /metrics
    static_configs:
      - targets: ["auth_service:3002"]

  - job_name: "pokemon_data"
    metrics_path: /metrics
    static_configs:
      - targets: ["pokemon_data:3001"]
