global:
  scrape_interval: 15s

rule_files:
  - alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "auth_service"
    metrics_path: /metrics
    static_configs:
      - targets: ["authentication_container:3002"]

  - job_name: "receiver_service"
    metrics_path: /metrics
    static_configs:
      - targets: ["receiver_service:3003"]

  - job_name: "storage_service"
    metrics_path: /metrics
    static_configs:
      - targets: ["storage_service:3004"]

  - job_name: "pokemon_data"
    metrics_path: /metrics
    static_configs:
      - targets: ["pokemon_data:3001"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "kafka_exporter"
    metrics_path: /metrics
    static_configs:
      - targets: ["kafka_exporter:9308"]
