formatters:
  detailed:
    format: '%(timestamp)s - %(level)s - %(message)s'
handlers:
  console:
    level: 'debug'
    type: 'console'
    formatter: 'detailed'
  file:
    level: 'debug'
    type: 'file'
    filename: 'app.log'
    formatter: 'detailed'
loggers:
  basicLogger:
    level: 'debug'
    handlers: ['console', 'file']
