# discover docker compose

version: '3.8'

services:
  discover_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: adamwentworth/discover_service:latest
    container_name: discover_service
    env_file:
      - .env
    ports:
      - "3006:3006"
    networks:
      - kafka_default

# No MySQL container here â€” using external DB

networks:
  kafka_default:
    external: true
