version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    volumes:
      - ./data/zookeeper:/opt/zookeeper-3.4.13/data
    networks:
      - kafka_default

  kafka:
    image: wurstmeister/kafka
    depends_on: [zookeeper]
    ports:
      - "127.0.0.1:9093:9093"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # Two listeners: INTERNAL for containers, EXTERNAL for host
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://127.0.0.1:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_CREATE_TOPICS: "batchedUpdates:1:1"
      KAFKA_BROKER_ID: 1
      KAFKA_MESSAGE_MAX_BYTES: "3145728"
      KAFKA_REPLICA_FETCH_MAX_BYTES: "3145728"
    volumes:
      - ./data/kafka:/kafka
    networks:
      kafka_default:
        aliases:
          - kafka

networks:
  kafka_default:
    external: true
