services:
  location_db:
    image: postgis/postgis:17-3.4
    container_name: location_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - location_pgdata:/var/lib/postgresql/data
      - ./init-sql:/docker-entrypoint-initdb.d
    networks:
      - kafka_default

  location_service:
    image: adamwentworth/location_service:latest
    container_name: location_service
    restart: unless-stopped
    ports:
      - "3007:3007"
    depends_on:
      - location_db
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: location_db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      SERVER_PORT: 3007
    networks:
      - kafka_default

volumes:
  location_pgdata:

networks:
  kafka_default:
    external: true
