version: 1
formatters:
  simple:
    format: '%(asctime)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  detailed:
    format: '%(asctime)s - %(levelname)s - trace_id: %(trace_id)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
filters:
  add_trace_id:
    (): storage.logging_filters.AddTraceIDFilter
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: detailed
    filters: [add_trace_id]
    filename: 'storage/app.log'
loggers:
  basicLogger:
    level: DEBUG
    handlers: [console]
    propagate: no
  fileLogger:
    level: DEBUG
    handlers: [file]
    propagate: no
  backupLogger:
    level: DEBUG
    handlers: [console, file]
    propagate: no
root:
  level: DEBUG
  handlers: [console, file]
