# authentication docker-compose

services:
  mongo_auth:
    image: mongo:6
    container_name: mongo_auth
    restart: unless-stopped
    volumes:
      - mongo_auth_data:/data/db
      - ./backups:/backups
    networks:
      - kafka_default

  auth_service:
    image: ${AUTH_IMAGE:-adamwentworth/authentication:latest}
    container_name: authentication_container
    ports:
      - "127.0.0.1:3002:3002"
    env_file:
      - .env
    depends_on:
      - mongo_auth
    restart: unless-stopped
    volumes:
      - ./backups:/usr/src/app/backups
    networks:
      - kafka_default

volumes:
  mongo_auth_data:

networks:
  kafka_default:
    external: true
